#!/usr/bin/env php
<?php

include __DIR__ . '/hooks-by-category.php';

$wiki_url = 'https://wiki.civicrm.org/confluence/display/CRMDOC';
$cache_dir = __DIR__ . '/wiki_cache';

chdir($cache_dir);

foreach ($hooks_by_category as $category => $hooks) {
  foreach ($hooks as $hook) {
    if ( file_exists($hook) ) {
      echo "SKIPPING: $hook (already cached)" . PHP_EOL;
    }
    else {
      echo "DOWNLOADING: $hook" . PHP_EOL;
      system("curl '$wiki_url/$hook' > '$hook'");
    }
    echo PHP_EOL;
  }
}

echo "DONE" . PHP_EOL;


