<?php

$hooks_by_category = [
  "Database" => [
    "hook_civicrm_copy",
    "hook_civicrm_custom",
    "hook_civicrm_managed",
    "hook_civicrm_merge",
    "hook_civicrm_post",
    "hook_civicrm_pre",
    "hook_civicrm_trigger_info",
    "hook_civicrm_referenceCounts",
    "hook_civicrm_postSave_table_name",
  ],
  "Extension lifecycle" => [
    "hook_civicrm_disable",
    "hook_civicrm_enable",
    "hook_civicrm_install",
    "hook_civicrm_uninstall",
    "hook_civicrm_upgrade",
    "hook_civicrm_postInstall",
  ],
  "Form" => [
    "hook_civicrm_alterContent",
    "hook_civicrm_buildForm",
    "hook_civicrm_postProcess",
    "hook_civicrm_validateForm",
    "hook_civicrm_alterTemplateFile",
    "hook_civicrm_preProcess",
    "hook_civicrm_idsException",
  ],
  "GUI" => [
    "hook_civicrm_buildAmount",
    "hook_civicrm_caseSummary",
    "hook_civicrm_customFieldOptions",
    "hook_civicrm_dashboard",
    "hook_civicrm_links",
    "hook_civicrm_navigationMenu",
    "hook_civicrm_pageRun",
    "hook_civicrm_searchColumns",
    "hook_civicrm_searchTasks",
    "hook_civicrm_summary",
    "hook_civicrm_summaryActions",
    "hook_civicrm_tabs",
    "hook_civicrm_xmlMenu",
    "hook_civicrm_tabset",
    "hook_civicrm_dashboard_defaults",
    "hook_civicrm_contact_get_displayname",
    "hook_civicrm_fieldOptions",
    "hook_civicrm_alterMenu",
  ],
  "Mail" => [
    "hook_civicrm_alterMailParams",
    "hook_civicrm_emailProcessor",
    "hook_civicrm_emailProcessorContact",
    "hook_civicrm_mailingGroups",
    "hook_civicrm_postEmailSend",
    "hook_civicrm_alterMailer",
    "hook_civicrm_unsubscribeGroups",
    "hook_civicrm_alterMailContent",
    "hook_civicrm_postMailing",
  ],
  "Permission" => [
    "hook_civicrm_aclGroup",
    "hook_civicrm_aclWhereClause",
    "hook_civicrm_alterAPIPermissions",
    "hook_civicrm_permission_check",
    "hook_civicrm_permission",
    "hook_civicrm_selectWhereClause",
  ],
  "Uncategorized" => [
    "hook_civicrm_alterCalculatedMembershipStatus",
    "hook_civicrm_alterBarcode",
    "hook_civicrm_alterBadge",
    "hook_civicrm_alterPaymentProcessorParams",
    "hook_civicrm_alterSettingsFolders",
    "hook_civicrm_alterSettingsMetaData",
    "hook_civicrm_apiWrappers",
    "hook_civicrm_buildStateProvinceForCountry",
    "hook_civicrm_config",
    "hook_civicrm_contactListQuery",
    "hook_civicrm_cron",
    "hook_civicrm_dupeQuery",
    "hook_civicrm_export",
    "hook_civicrm_import",
    "hook_civicrm_membershipTypeValues",
    "hook_civicrm_tokens",
    "hook_civicrm_tokenValues",
    "hook_civicrm_queryObjects",
    "hook_civicrm_check",
    "hook_civicrm_optionValues",
    "hook_civicrm_coreResourceList",
    "hook_civicrm_angularModules",
    "hook_civicrm_container",
    "hook_civicrm_crudLink",
    "hook_civicrm_fileSearches",
    "hook_civicrm_notePrivacy",
    "hook_civicrm_eventDiscount",
    "hook_civicrm_recent",
    "hook_civicrm_unhandledException",
    "hook_civicrm_alterMailingLabelParams",
    "hook_civicrm_geocoderFormat",
    "hook_civicrm_alterLogTables",
  ],
  "Case" => [
    "hook_civicrm_caseChange",
    "hook_civicrm_caseTypes",
    "hook_civicrm_post_case_merge",
    "hook_civicrm_pre_case_merge",
  ],
  "Batch" => [
    "hook_civicrm_batchItems",
    "hook_civicrm_batchQuery",
  ],
  "Entity" => [
    "hook_civicrm_entityTypes",
  ],
  "CiviRules" => [
    "hook_civirules_alter_trigger_data",
    "hook_civirules_logger",
  ],
  "Profile" => [
    "hook_civicrm_buildProfile",
    "hook_civicrm_buildUFGroupsForModule",
    "hook_civicrm_processProfile",
    "hook_civicrm_searchProfile",
    "hook_civicrm_validateProfile",
    "hook_civicrm_viewProfile",
  ],
  "Report" => [
    "hook_civicrm_alterReportVar",
  ]
];