#!/usr/bin/env php
<?php

include __DIR__ . '/hooks-by-category.php';

$cache_dir = __DIR__ . '/wiki_cache';
$root_dir = dirname(dirname(__DIR__));
$hooks_dir = "$root_dir/docs/hooks";

# create hooks directory if needed
if ( !is_dir($hooks_dir) ) {
  mkdir($hooks_dir);
}

chdir($hooks_dir);

foreach ($hooks_by_category as $category => $hooks) {
  foreach ($hooks as $hook) {
    $html = "$cache_dir/$hook";
    if ( file_exists($html) ) {
      echo "converting $hook ... ";
      $conversion_status = 1;
      system("webpage2md $html > $hook.md", $conversion_status);
      if( $conversion_status == 0 ) {
        echo "done" . PHP_EOL;
      }
      else {
        echo "ERROR CONVERTING $hook" . PHP_EOL;
      }
    }
    else {
      echo "WARNING: $hook not yet fetched" . PHP_EOL;
    }
  }
}




