#!/usr/bin/env php
<?php

include __DIR__ . '/hooks-by-category.php';

foreach ($hooks_by_category as $category => $hooks) {
  foreach ($hooks as $hook) {
    $hook_name = $hook['name'];
    echo "$hook_name hooks/$hook_name" . PHP_EOL;
  }
}
