#!/usr/bin/env php
<?php

include __DIR__ . '/hooks-by-category.php';

foreach ($hooks_by_category as $category => $hooks) {
  foreach ($hooks as $hook) {
    echo "$hook hooks/$hook" . PHP_EOL;
  }
}
